Master updates
symfonyse/symfony.se pull request #46
Opened 2017-03-26 08:35 UTC by rashidfawad

I have updated Symfony from 2.3 to 2.8 along with some other dependencies. I have also removed some deprecations. The November Camp page route did not have any Controller specified.  Perhaps we can fix it after you review the changes. 

Cheers

2017-03-29 16:44 UTC, Nyholm requested changes
Awesome. Thank you. Ive reviewed this PR and tested it. I like it. I only had a few comments. 

A question, Why did you change all the file permissions?

2017-03-30 05:24 UTC, rashidfawad commented
Than you for review. I have added Twig/Extensions, replaced tilde with caret in composer. I could use FrameworkBundle TemplateAction for rendering the november-camp page but then I did not have the template so I skipped it. As each page is built using small text portions.
Regarding the file permissions usually when I need to change multiple files, I usually do "sudo chmod -R 777 abc" to make it editable :).

2017-03-30 05:54 UTC, Nyholm commented
Thank you. 
If you revert the file permissions, I'll be happy to merge. We do not need the world to be able to edit the source.

2017-04-01 15:24 UTC, rashidfawad commented
Hi, I can't change the permissions to 644 because when I change it I can no longer use git to commit the changes. I also could not use symfony.se the first time I cloned it from Github. I had to change the permission then I could access the site on localhost. 

If you can change the permissions, kindly do it and then merge it. Thank you.

2017-04-02 14:13 UTC, Nyholm reviewed
There were some issues and fixed that has not been completed here. 

Ie, the test code did not run. I have fixed those and created a new PR.

2017-04-02 14:13 UTC, Nyholm commented on composer.json
> +        "twig/twig": "^1.0||^2.0",
Why do we want to support both?
Also, it fails under twig 2.0

2017-04-02 14:13 UTC, Nyholm commented on composer.json
> +        "debril/rss-atom-bundle": "^3.0.5",
What were the BC breaks between 1.3.2 and ^3.0.5? I can see some that has not been taken care of.

2017-04-02 14:15 UTC, merged

2017-04-02 14:15 UTC, Nyholm commented
Ive merged the changes. Thank you for this PR.

2017-04-02 14:35 UTC, rashidfawad commented
I can't access the site. Can you check the logs on the server where the problem is? It's giving me 500 error.

2017-04-02 14:40 UTC, rashidfawad commented on composer.json
> +        "twig/twig": "^1.0||^2.0",
No, we don't have to support both. We should update it to the latest if we want to switch to Symfony3.  If there is some deprecation warning or BC break by using version 1.0. I can remove it. It was working for me on localhost.

2017-04-02 15:58 UTC, Nyholm commented
FIxed now. I added PHP7 and HTTPS

2017-04-03 03:49 UTC, rashidfawad commented
Yuup, saw it. The error may have occurred because we were referencing Http links from Https.